### PR TITLE
fixing f.bits size inconsistency #7

### PR DESCRIPTION
**Pull request by thomasjungblut**
fix for #7, in my vendor folder it makes me successfully read the bloom filter.

### CODE REVIEW

**Comment by damz** [comment]
It is the unmarshaler that is totally bogus. I have this fix in my workspace:

```diff
--- a/binaryunmarshaler.go
+++ b/binaryunmarshaler.go
@@ -57,7 +57,7 @@ func (f *Filter) UnmarshalBinary(data []byte) (err error) {
                return err
        }
 
-       f.bits = make([]uint64, f.n)
+       f.bits, _ = newBits(f.m)
        err = binary.Read(buf, binary.LittleEndian, f.bits)
        if err != nil {
                return err
```

**Comment by steakknife** [comment]
Now I understand there's a problem. Fixing..

**Comment by steakknife** [comment]
Fixed in cbf8825

**Comment by damz** [comment]
@steakknife Note that the fix broke compilation.

**Comment by steakknife** [comment]
Yup. ;) I fixed it but didn't update the comment.

**Comment by steakknife** [comment]
Oh gometalinter... refactoring nocturnal spelunking. Great.

**Comment by steakknife** [comment]
Fixed. TY for following-up.

**Pull request closed without merging**
